### ISSUE TITLE
gobig not going big

### ISSUE THREAD

**Issue by eformx** [lowfuel/progrockdiffusion#104]
I ran 4 batches at 256x384 and have gobig scale set for 2x and the results were still 256x384.  I would expect them to be 512x768?  No erros on the run. My settings:

`"width": 384,
    "height": 256,
    "gobig_orientation": "vertical",
    "gobig_scale": 2,
    "gobig_skip_ratio": 0.6,`

And just wondering if the scale is applied to the partial images or the final one?

**Comment by lowfuel** [comment]
What was your command line?

**Comment by eformx** [comment]
just  `python prd.py`

**Comment by lowfuel** [comment]
Ah, okay. It's a special mode so you have to add this to your command line:
```
python prd.py --gobig
```

**Comment by lowfuel** [comment]
And please note, the initial image will still be the regular size. Once it finishes it the gobig upscaling will start. In the end you'll have the original image and the upscaled version.
