### ISSUE TITLE
Run txt2img from 512x512_diffusion_uncond_finetune_008100 model?

### ISSUE THREAD

**Issue by eformx** [lowfuel/progrockdiffusion#113]
Just wondering if this is possible as it would save downloading the 6gb model and allow the user to fine tune the result with the prog rock diffusion settings/json

**Comment by eformx** [comment]
It's in the latent-diffusion folder. It allows you to create a mask around something you want to remove.  There is a mod here: https://github.com/loboere/latent-diffusion-inpainting-colab/blob/main/scripts/txt2img.py where you can create a mask in an image and replace it with the result from a prompt.  It currently uses a different model then the fine tune version and thus has less refinement over the results. I thought it would be quite cool if you could us the diffusion model and json settings to really spruce up the results.  Imagine memes, marketing posters all augmented by AI In Painting.

**Comment by lowfuel** [comment]
Ah, I see what you mean now. I misunderstood. The intent of render_mask is different, it's to take an existing image and re-render parts of it with a different prompt or settings, then composite back over the original image. It doesn't (Disco Diffusion doesn't) know how to only use certain parts of the canvas like your example is doing. 

I can look into that but I haven't seen anything in Disco's code that would make this possible. Latent diffusion's renderer is a totally different beast.

**Comment by KnoBuddy** [comment]
I would love to see inpainting like with Latent Diffusion. I've been scrambling to even find time to dig into ProgRock's code, so I have no idea if this is even possible...

**Comment by lowfuel** [comment]
I have a possible method I'm experimenting with today. Will keep you posted!

**Comment by lowfuel** [comment]
![Default_366_0](https://user-images.githubusercontent.com/18050333/180069331-51733d46-c52d-47c2-af8c-2e6b9bad80ee.png)

My crappy prompt aside, making some progress.

**Comment by lowfuel** [comment]
I checked in the init_masked stuff just now, so let me know how you get on.
As you can see in the image above, on the left is the classic init_image, in the middle is the render_mask (which is saying to apply the white areas over the init_image and leave the black areas alone), and then finally on the right is init_masked, which is essentially an alternative init_image that it uses for the render instead of the original one.
A bit cumbersome I know, but it's the best I've got for now. :)

**Comment by lowfuel** [comment]
Yeah it should have! Weird. I just tested it yesterday too. Maybe I messed something up though. Can you post your settings so I can double check them?

**Comment by lowfuel** [comment]
Just tested it again here and it's working for me.

**Comment by eformx** [comment]
Ran it again, ,still not working.  It looks like you apply the changes in

`if letsgobig: `

where I am not using gobig, the slice is not applied. I am using a Real-ESRGAN.

**Comment by lowfuel** [comment]
You need to specify a render mask, otherwise it doesn't know what to keep from the new image.

**Comment by eformx** [comment]
Can you provide your settings so we know exactly what is what?  I got an error running it...

the main settings:
`"init_image": null,
    "init_masked": "input/mask.png",
    "render_mask": "input/img.png",`

Where mask is the black image with white circles. render_mask is the house in the lavender fields.  Is the house supposed to go in init_image?  and then what goes in render_mask?

`Prompt for step 0: ['planets trending on artstation']
Image 1 of 1: : 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [17:18<00:00, 103.89s/it]
Using render mask to composite rendered image with init image.


All image(s) finished.
Traceback (most recent call last):
  File "D:\sites\progrockdiffusion\prd.py", line 3049, in <module>
    do_run(batch_image)
  File "D:\sites\progrockdiffusion\prd.py", line 1787, in do_run
    image3 = Image.alpha_composite(init_img, image3)
UnboundLocalError: local variable 'init_img' referenced before assignment
`

**Comment by eformx** [comment]
Running it again.  Looks like these are the 'image' settings based on the context definition above:

`"init_image": "input/img.png",
    "init_masked": null,
    "render_mask": "input/mask.png",`

**Comment by lowfuel** [comment]
Here's what I used for the image above:
```
    "init_image": "init_images/planet.png",
    "init_masked": "init_images/planet_init_mask.png",
    "render_mask": "init_images/planet_mask2.png",
```

**Comment by eformx** [comment]
Can you clarify which of your 4 images is which? planet could be image 3 or 4, which one planet_mask2?  I have 2 images, the lavender fields and a mask. Does the user have teo create a third one?

**Comment by lowfuel** [comment]
The three I just listed are the three across the top of the above image, in that order.

init_image: the original image
render_mask: black is the areas to keep from init_image, white is the areas to keep from init_masked
init_masked: the init image to use for this render, composited on top of the original init_image

You don't have to provide an init_masked, if you don't it will use noise in those areas just like if you were running without an init.

**Comment by eformx** [comment]
Yes this work greate. Thanks!

"init_image": "input/img.png", "init_masked": "input/mask.png", "render_mask":  "input/mask.png"
