### ISSUE TITLE
Save clip models to local directory?

### ISSUE THREAD

**Issue by eformx** [lowfuel/progrockdiffusion#115]
It looks like the clip models are stored in a cache on the local machine which works for most use cases; however if we use google colab it basically redownloads them each time when you reopen the notebook.  

Is there a way to save them in a folder and then load them from there? Not sure if this is possible in progrock?

I also have gpu's that I load stuff into remotely; which means they have to download the clip models over and over.  The dd finetune model is in a folder.  Can the clip models  be loaded from a folder, not cache?

`"RN50": "https://openaipublic.azureedge.net/clip/models/afeb0e10f9e5a86da6080e35cf09123aca3b358a0c3e3b6c78a7b63bc04b6762/RN50.pt",`

**Comment by lowfuel** [comment]
It is possible for the standard OpenAI CLIP models, but not (as far as I can tell) for the OpenClip models. So, I will change it so that the standard CLIP models are stored in our models folder like the finetune models, but if you use OpenClip models they'll still be stored in cache.

**Comment by lowfuel** [comment]
Er... just to be clear, are you talking about in progrock or some notebook? (And if notebook, which one?)

**Comment by eformx** [comment]
In progrock.

**Comment by eformx** [comment]
Do you know where in the code the OpenClip models are downloaded?  I don't see any URL's for them in the code.

**Comment by lowfuel** [comment]
It's within OpenClip's code inside pretrained.py I think

**Comment by lowfuel** [comment]
Probably should file an issue with them asking to support the download_root option ala CLIP, instead of relying soley on a hardcoded directory.

By the way I am probably going to make changing the directory an option in PRD, rather than the default. 
While I understand your use case, I've already discovered it's not ideal to have to have copies of all the CLIP models in every directory I have for PRD, rather than all of them sharing one cache directory. I usually have 2 or 3 PRD directories I use for various reasons (testing new stuff, testing the current version, testing old versions), plus several other tools I've written that also use CLIP, and now I'm having to copy the models folder to every one of them. I know others who use PRD as well as Disco and other versions of Disco on their local machine who appreciate the shared models, too.

**Comment by klossm** [comment]
I changed the default path of the cache of some models to other drive letters. By default, it takes up too much space on disk C, so I changed it to disk D. the default path is in C:\ Users\ Administrator\ .cache.

Open clip.py in\ progrockdiffusion\ CLIP\ clip, search for the cache keyword, and change it to.
Path to download the model files; by default, it uses "D:\\ Users\\ Administrator\\ .cache\\ clip"

Model_path = _ download (_ MODELS [name], download_root or os.path.expanduser ("D:\\ Users\\ Administrator\\ .cache\\ clip")).


Open pretrained.py in\ progrockdiffusion\ open_clip\ src\ open_clip.
Search for the cache keyword and change it to.

Def download_pretrained (url: str, root: str = os.path.expanduser ("D:\\ Users\\ Administrator\\ .cache\\ clip"):

**Comment by klossm** [comment]
But I haven't found a way to modify the cache path in this directory.
C:\ Users\ Administrator\ .cache\ torch\ hub\ checkpoints.
Can someone tell me where to modify it?

**Comment by eformx** [comment]
I didn't even have openclip in the project, but worked perfectly fine lol.  have it now. will look into the paths stuff as well. @lowfuel  just wondering how you are making out with this enhancement?

**Comment by lowfuel** [comment]
Should have it checked in later today, just testing a few other things first

**Comment by lowfuel** [comment]
> I didn't even have openclip in the project, but worked perfectly fine lol. have it now. will look into the paths stuff as well. @lowfuel just wondering how you are making out with this enhancement?

It's in now. The README has details but basically set an environment variable for LOCAL_CLIP_MODELS to TRUE (or anything really) and it will store them in the PRD models directory.

**Comment by eformx** [comment]
Works great!  Thanks! Updated prd.py and clip_manager.py and good to go.
