### ISSUE TITLE
Gui Option throws error

### ISSUE THREAD

**Issue by KnoBuddy** [lowfuel/progrockdiffusion#116]
Okay so I've spent some time digging through the current prdgui.py. The original error I got was

```
Traceback (most recent call last):
  File "C:\Users\kyle\progrockdiffusion\prdgui.py", line 77, in run
    self.func()
TypeError: do_run() missing 1 required positional argument: 'batch_num'

```

After moving `prdgui.rungui(do_run(), side_x, side_y)` a few lines down in prd.py and changing it to `prdgui.run_gui(do_run(batch_image), side_x, side_y)` I get a new error: 

```Traceback (most recent call last):
  File "prd.py", line 2859, in <module>
    prdgui.run_gui(do_run(batch_image), side_x, side_y)
  File "prd.py", line 1741, in do_run
    prdgui.update_image(image)
  File "C:\Users\kyle\progrockdiffusion\prdgui.py", line 94, in update_image
    window.setPixmap(img)
AttributeError: 'NoneType' object has no attribute 'setPixmap'
```

I have played around with the code and it seems that the global variable `window` is not being changed from the value `None` to `Window(worker_func, width, height)`, or at least it is not sticking? I don't have a clue. There is was too much OOP going on. My head explodes with all the constructors and self and idk... I need to go back to the basics.

**Comment by lowfuel** [comment]
Personally, I think the answer might be to simply create a GUI that can read/write settings files, provide controls and input mechanisms for those settings, and select command line options, and then fire off prd.py and display the results as they render. I don't see a major reason to having the gui be inside prd itself, at least off the top of my head.

**Comment by KnoBuddy** [comment]
I decided to play with tkinter today and see what I could come up with. So far so good, quite a ways to go though.
![image](https://user-images.githubusercontent.com/64171756/180576794-65149491-d5e3-41b6-96de-e91872aa8809.png)

**Comment by lowfuel** [comment]
Nice!

One thing you might consider as you lay it out is perhaps having only the really key variables exposed initially, with an "advanced" button that would show the rest. Not sure if that's possible with tkinter, so just take it as a suggestion. :)

**Comment by KnoBuddy** [comment]
Honestly, my main goal is simply to be able to easily view and create images, as well as edit settings and prompts in an easy way from my phone. I tired setting up a discord or telegram bot but can't get a conda env set up. I guess I could just do a toot python install since it's a VM anyways. 

Anyways I'm gonna keep working on it because I need to practice my skills anyways, but if you guys got any ideas or suggestions to make using PRD easier please chime in.

**Comment by lowfuel** [comment]
Yeah you could totally just have a direct install, conda is not required it just makes it easy to have a contained environment.
There are several people on Discord who have setup PRD to run via a Discord bot that might be able to help you there (reach out to bit_FLIP on the Disco Diffusion discord, he has one called Synthia).

**Comment by KnoBuddy** [comment]
Long ways to go but we are getting there. Currently it auto populates a few of the fields and allows you to save the settings file, as well as run from command line. It currently displays the progress.png but refresh functionality doesn't work. Also it will error if there is no progress.png file so make sure there is one in the directory.

Here's the progress, I want to get most of the features done before I do a PR.

![image](https://user-images.githubusercontent.com/64171756/180625857-4972b517-2fbf-420c-bb9c-718f230fa8fa.png)
https://github.com/KnoBuddy/prdgui/blob/main/prdgui.py

**Comment by KnoBuddy** [comment]
Developed new GUI myself so issue closed.

**Comment by lowfuel** [comment]
That's one way to get issues fixed! :D
