### ISSUE TITLE
UserWarning pauses run and then restarts

### ISSUE THREAD

**Issue by eformx** [lowfuel/progrockdiffusion#117]
Used default settings.json and get this error message (worked fine the other day).  Is there any way to suppress these and continue like it did?

`Prompt for step 0: ['A beautiful painting of a Castle in the Scottish Highlands, underexposed and overcast, by Asher Brown Durand, trending on ArtStation.']
High contrast corrected at step 30                                              
Image 1 of 1: :  12%|███                       | 29/250 [00:51<06:29,  1.76s/it]/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /tmp/pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
High contrast corrected at step 40                                              
High contrast corrected at step 60                                              
Image finished. Using seed 2738888603 for next image.                           
Image 1 of 1: : 100%|█████████████████████████| 250/250 [08:22<00:00,  2.01s/it]`

**Comment by lowfuel** [comment]
That's a new one to me. Did it prevent the render or was it truly just a warning?

Anything change on your system that might have caused this? Did you reinstall pytorch or any of the other components prd uses?

**Comment by eformx** [comment]
It might be a pytorch version difference. remote is running 3.8 and local 3.9 which works fine, will try 3.9 remote and will let you know.

**Comment by eformx** [comment]
narrowed it down to hosting issue. you can close this.
