### ISSUE TITLE
Change Guided-Diffusion library?

### ISSUE THREAD

**Issue by mhop1** [lowfuel/progrockdiffusion#119]
Disco Diffusion seems to have switched from:

https://github.com/crowsonkb/guided-diffusion.git

to:

https://github.com/kostarion/guided-diffusion.git

as the 2nd one seems more up to date?

**Comment by lowfuel** [comment]
The only changes (other than to the Disco notebook it includes, which we don't need) are related to symmetry, which we already have from another method. So at the moment I don't see a good reason to change over, unless I missed something?

**Comment by mhop1** [comment]
Ok. Closing this.
