### ISSUE TITLE
clip_guidance_scale does not work if set to 'random'

### ISSUE THREAD

**Issue by eformx** [lowfuel/progrockdiffusion#121]
As per settings.md if you set clip_guidance_scale to 'random' it should pickup a random value.  In my testing and as per the code at line 941 it's looking for 'auto'

'# Automatic clip_guidance_scale based on overall resolution
if clip_guidance_scale == 'auto':'

If you run it with 'random' it breaks.  If you run it with 'auto' it works.

In short add a section to settings.md for settings that accept 'auto', remove clip_guidance_scale from the 'random' docs.

**Comment by lowfuel** [comment]
Nice find, thanks. This will be fixed in my next checkin (and will work for both auto and random again).
