### ISSUE TITLE
Cannot get GUI working

### ISSUE THREAD

**Issue by captain-git-planet** [lowfuel/progrockdiffusion#125]
running the prdgui.py script is not bringing up a window

**Comment by KnoBuddy** [comment]
PRD works normally from command line?

**Comment by eformx** [comment]
I am running it inside PyCharm, all works great :)

**Comment by captain-git-planet** [comment]
> PRD works normally from command line?
> 
> You need to be inside of the conda environment, as well as inside the repo's working directory when you run:
> 
> ```
> python prdgui.py


> ```

yep, I am inside conda env and inside the directory, and prd.py works fine too! When I run prdgui.py it just goes to the next line nothing comes up

![nothing happens](https://user-images.githubusercontent.com/62304502/181293954-ca10acc7-2096-40a9-b832-6e6efef74103.PNG)

**Comment by captain-git-planet** [comment]
I will give that a try and report back, thank you!

**Comment by captain-git-planet** [comment]
I was able to get the GUI working with the latest changes!
