### ISSUE TITLE
 Questions about prdgui.py

### ISSUE THREAD

**Issue by klossm** [lowfuel/progrockdiffusion#129]
Frame1, diffusion_model_text, '512x512 diffusionsionunconditons finetune008120 in prdgui.py, is the name wrong? It should be 512x512_diffusion_uncond_finetune_008100.pt. There seems to be a mistake in the Mantissa.Save when the name is wrong, and then running will cause an error in the run。

**Comment by KnoBuddy** [comment]
Solved in /pull/131
