### ISSUE TITLE
Swapping models in prd.gui breaks

### ISSUE THREAD

**Issue by captain-git-planet** [lowfuel/progrockdiffusion#135]
Recently had been using the default gui settings, but swapped to portrait_generator_v001. Had no issues doing that, but now whenever I try to change models away from portrait_generator_v001, I get a 

`Traceback (most recent call last):
  File "prd.py", line 2290, in <module>
    download_models(diffusion_model, use_secondary_model)
  File "prd.py", line 2227, in download_models
    model_file = f'{model_path}/{diffusion_model.path}'`

error

the prompt I'm trying to run runs fine using the regular command line, and the prompt also runs if I don't change from portrait mode. Tried updating to most recent version too!

**Comment by captain-git-planet** [comment]
full reinstall fixed it

**Comment by KnoBuddy** [comment]
That happens when the downloaded file is partial or corrupt. Deleting the model and rerunning prd.py will redownload it and fix it normally for the future.
