### ISSUE TITLE
Leaving prompts blank in prd gui will break it the next time you open it

### ISSUE THREAD

**Issue by captain-git-planet** [lowfuel/progrockdiffusion#142]
**to reproduce:**

Delete all text from prompts

input an extra argument (can be anything, but for example "-s settings.json")

run the empty prompt 

close and reopen prd.gui

![image](https://user-images.githubusercontent.com/62304502/183229851-19b5cc27-6e2b-4650-aa8f-ecbe3f4f9412.png)

Was able to unlock it by going into gui_settings and inputting any random word into the empty text_prompts. I only ran into this because I was running custom settings files with extra args

**Comment by KnoBuddy** [comment]
I'll see if I can squash this or put in a failsafe if the settings file fails to load when I get a chance to work on the GUI tomorrow.

**Comment by KnoBuddy** [comment]
Fixed in /pull/146.

**Comment by lowfuel** [comment]
Merged!

**Comment by captain-git-planet** [comment]
awesome, thanks all!
