### ISSUE TITLE
Put settings in PNG metadata

### ISSUE THREAD

**Issue by lowfuel** [lowfuel/progrockdiffusion#15]
Another idea I had last night is to put the settings used directly into the ouput's EXIF data (I think there's a 'comments' field you can put free-form text in). Just as a way to have settings in the image rather than needing to keep all the settings files around with them.

**Comment by lowfuel** [comment]
Putting this idea on hold. I can't find an exif library that works well AND supports PNG files.

**Comment by grok13** [comment]
if it helps, this is what this repo was doing: https://github.com/rbbrdckybk/ai-art-generator

**Comment by lowfuel** [comment]
Thanks @grok13 ! I checked out their code and it seems they get around the PNG issue by converting to a JPG first. I'm not loving that as a solution as there's probably a loss of image quality in converting.

I'll probably hold off still, unless there is enough demand for this feature that people are willing to risk some compression of their image.

**Comment by lowfuel** [comment]
Hi everyone. FYI, I didn't find a good way to put the settings into EXIF data, but I did discover that the PNG file format supports arbitrary metadata, and we were already using the library that supports it!

So I've added what I consider the most important settings as metadata in the final output images.

# IF YOU DON'T WANT YOUR PROMPTS AND 'SECRET SAUCE' SETTINGS STORED IN YOUR OUTPUT, PLEASE ADD --hidemetadata TO YOUR COMMAND LINES. Or strip the metadata on images you share publicly, if that's your concern.

Otherwise, please enjoy that you now can (fairly) safely clean up old settings files with the confidence that you can still retrieve the prompt and random seed used in a given image.
