### ISSUE TITLE
clamp_max settings issue

### ISSUE THREAD

**Issue by tuwonga** [lowfuel/progrockdiffusion#163]
Hello,
when I try to change the clamp_max from auto to 0.05 or another value I have this error:

###   
    File "prd.py", line 1624, in cond_fn
    return grad * magnitude.clamp(max=args.clamp_max[1000 - t_int]) / magnitude
    TypeError: 'float' object is not subscriptable
    
    The only way is using clamp_max : auto
    
    Thank you

**Comment by KnoBuddy** [comment]
It must be defined as a schedule.

If you want one setting the entire length of the diffusion process you would set it to [0.15]*1000.

If you wanted it to be for the first 20% then another for the last 80% it would be like [0.15]*200+[0.10]*800.

The total must add up to 1000.

**Comment by lowfuel** [comment]
KnoBuddy is probably right, but I thought it would support either format, so I'll take a look. In any case, you can use his suggestion for the short term.

**Comment by tuwonga** [comment]
thank you both of you guys !!!
