### ISSUE TITLE
cuda out of memory , but there is enough memory

### ISSUE THREAD

**Issue by MrDeemoZe** [lowfuel/progrockdiffusion#23]
I'm using a 3090 to run this file.  I set the width: 1920 and height: 1080 and result in the error below.
OS：win10 21H2
Memory：32G
GPU：3090
RuntimeError: CUDA out of memory. Tried to allocate 1.88 GiB (GPU 0; 24.00 GiB total capacity; 7.97 GiB already allocated; 9.14 GiB free; 12.15 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by lowfuel** [comment]
That error comes from pytorch, not progrockdiffusion, and although the numbers are a bit odd, the gist is still accurate: you ran out of GPU memory.

Try lowering the resolution in increments of 64 until it works. Also, FYI, the resolution needs to be a multiple of 64, so 1080 won't work. I mean, it will run, but it will automatically change it to the nearest 64 multiple.

I would try:

1856x1024

If you still get that error, just keep going down by 64 in each dimension until you find the sweetspot for your GPU.

**Comment by MrDeemoZe** [comment]
thanks a lot, lowering the resolution did work for me, though it's still weird that Pytorch didn't reserve more GPU memory since there are 9.14G free
[Issue here](https://github.com/pytorch/pytorch/issues/16417#issuecomment-846655906) said reducing the batch size may help, so is there a way to change the batch size?

**Comment by MrDeemoZe** [comment]
Thank you for your information! It's very helpful to me.

**Comment by polygonalminiatures** [comment]
HD is too high for 3090, try lowering the resolution.MarkSent from my Galaxy
-------- Original message --------From: MrDeemoZe ***@***.***> Date: 4/26/22  09:41  (GMT+01:00) To: lowfuel/progrockdiffusion ***@***.***> Cc: Subscribed ***@***.***> Subject: [lowfuel/progrockdiffusion] cuda out of memory , but there is enough memory (Issue #23) 

I'm using a 3090 to run this file.  I set the width: 1920 and height: 1080 and result in the error below.

OS：win10 21H2

Memory：32G

GPU：3090

RuntimeError: CUDA out of memory. Tried to allocate 1.88 GiB (GPU 0; 24.00 GiB total capacity; 7.97 GiB already allocated; 9.14 GiB free; 12.15 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by KnoBuddy** [comment]
You shouldn't have any issues with any normal size resolutions on a 3090. Pytorch should be reserving closer to 23GB not 12GB.

Obviously question but did you try restarting your computer? I've had issues where pytorch crashed and it kept the memory reserved until I ran some special commands or rebooted.
