### ISSUE TITLE
Not able to generate multiple frames 

### ISSUE THREAD

**Issue by jef-raven** [lowfuel/progrockdiffusion#25]
Hello,
I don't seem to be able to generate multiple frames by changing the max-frames amount. In the colab version of Disco-diffusion this value makes it so multiple frames are generated, one after the other . When I try changing this value I still only get 1 frame. I'm wondering if there is a way enable this. I tried adjusting a bunch of values in the settings, but nothing seems to work.
Any help is appreciated!

**Comment by polygonalminiatures** [comment]
Animation does not work currently, as far as I know.MarkSent from my Galaxy
-------- Original message --------From: jef-raven ***@***.***> Date: 4/30/22  17:41  (GMT+01:00) To: lowfuel/progrockdiffusion ***@***.***> Cc: Subscribed ***@***.***> Subject: [lowfuel/progrockdiffusion] Not able to generate multiple frames  (Issue #25) 
Hello,
I don't seem to be able to generate multiple frames by changing the max-frames amount. In the colab version of Disco-diffusion this value makes it so multiple frames are generated, one after the other . When I try changing this value I still only get 1 frame. I'm wondering if there is a way enable this. I tried adjusting a bunch of values in the settings, but nothing seems to work.
Any help is appreciated!

**Comment by jef-raven** [comment]
> ###

Ah I see, and what if I were to not use animation, could I still make a video somehow? I'm using both animation and changing the prompt over multiple frames.

**Comment by polygonalminiatures** [comment]
You can do batches but it will be a pain to watch :)MarkSent from my Galaxy
-------- Original message --------From: jef-raven ***@***.***> Date: 4/30/22  17:46  (GMT+01:00) To: lowfuel/progrockdiffusion ***@***.***> Cc: polygonalminiatures ***@***.***>, Comment ***@***.***> Subject: Re: [lowfuel/progrockdiffusion] Not able to generate multiple frames  (Issue #25) 



Ah I see, and what if I were to not use animation, could I still make a video somehow? I'm using both animation and changing the prompt over multiple frames.

**Comment by lowfuel** [comment]
> Ah I see, and what if I were to not use animation, could I still make a video somehow? I'm using both animation and changing the prompt over multiple frames.

Sorry, animations are currently not working. I'm still working on figuring out why.
