### ISSUE TITLE
How can I make it run faster?

### ISSUE THREAD

**Issue by fusichao** [lowfuel/progrockdiffusion#27]
Hello,
It takes about 20 minutes to generate one picture on my RTX-3070，then I try it on Tesla-V100, it takes almost the same time.  
Is there any tricks to make it run faster? thanks~

**Comment by lowfuel** [comment]
Can you share your settings for an image that takes that long?

On my 3080 a typical image with my settings takes about 8 minutes. A friend with a 3060 gets 12 minutes.

**Comment by fusichao** [comment]
I use the original settings.json without any change
[https://github.com/lowfuel/progrockdiffusion/blob/main/settings.json](url)

and make some changes in "text_prompts", also takes about 20 minutes

**Comment by lowfuel** [comment]
I'm not sure what to tell you then, sorry. There must be some other bottleneck.
The only ways I can suggest to improve speed are to lower the number steps, or cuts.
```
    "steps": 200,
    "cut_overview": "[5]*400+[1]*600",
    "cut_innercut": "[1]*400+[5]*600",
```
Should produce images faster but, of course, at the expense of some image quality.
You could always use those settings, and perhaps a lower resolution too, to get images faster for evaluating the quality of a prompt, then use the higher quality settings when you want to do a better version.

**Comment by fusichao** [comment]
I will try these options, thank you!
