### ISSUE TITLE
I can't use init_image 

### ISSUE THREAD

**Issue by felipedorosario** [lowfuel/progrockdiffusion#28]
Hello mate!

I'd like to thank you for all the work you are doing on this project, it's awesome!
Now, I have a question. When I try to set a initial image I get this:

(progrockdiffusion) PS C:\Users\sipir\progrockdiffusion>  python prd.py
Parsing settings.json
clip_guidance_scale set automatically to: 7277
Using device: cuda:0
512 Model already downloaded, check check_model_SHA if the file is corrupt
Secondary Model already downloaded, check check_model_SHA if the file is corrupt
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: C:\Users\sipir\anaconda3\envs\progrockdiffusion\lib\site-packages\lpips\weights\v0.1\vgg.pth
Starting Run: Default(7) at frame 0
Using seed 1568777124
Prepping model: C:\Users\sipir\progrockdiffusion/models/512x512_diffusion_uncond_finetune_008100.pt
Frame Prompt: {'0': ['Landscape with robots who fulfill the needs of the city inhabitants, along with the vibrant landscapes around glass made by the three dimensional material by RHADS and Peter Mohrbacher, trending on Artstation']}
skip steps: 500
 Prompt for step 0: ['Landscape with robots who fulfill the needs of the city inhabitants, along with the vibrant landscapes around glass made by the three dimensional material by RHADS and Peter Mohrbacher, trending on Artstation']
Fetching C:/Users/sipir/progrockdiffusion/init_images/geninit.png
This might take a while... please wait.
prd.py:1404: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  init = init.resize((args.side_x, args.side_y), Image.LANCZOS)
Batches:   0%|                                                                                                                                                | 0/5 [00:00<?, ?it/s]
Batches:   0%|                                                                                                                                                | 0/5 [00:00<?, ?it/s]
Batches:   0%|                                                                                                                                                | 0/5 [00:00<?, ?it/s]
Batches:  20%|███████████████████████████▏                                                                                                            | 1/5 [00:00<00:00, 17.41it/s]
Batches:  40%|█████████████████████████████████████████████████████████▌                                                                                      | 2/5 [00:00<?, ?it/s]
Batches:  40%|██████████████████████████████████████████████████████▍                                                                                 | 2/5 [00:00<00:00, 36.10it/s]
Batches:   0%|                                                                                                                                                | 0/5 [00:00<?, ?it/s]
Batches:  60%|█████████████████████████████████████████████████████████████████████████████████▌                                                      | 3/5 [00:00<00:00, 54.14it/s]
Batches:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                            | 4/5 [00:00<?, ?it/s]
Batches:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 4/5 [00:00<00:00, 73.60it/s]
Seed used: 1568777124

And then nothing happens 
I made the initial image the same size as the output. It shouldn't resize it. Am I doing something wrong?

**Comment by lowfuel** [comment]
Can you post the settings file, and what your command line is?
Please note you have to put text between triple ` characters to get it to format correctly, so type three of those, press enter, paste your settings, then add three more, like this:
```
this is correctly formatted
```

**Comment by lowfuel** [comment]
Cannot troubleshoot without settings.
