### ISSUE TITLE
Change batch_name cause issue at line 2740

### ISSUE THREAD

**Issue by hydropix** [lowfuel/progrockdiffusion#32]
Hi :) 
I got this error after changing the batch_name.

_python .\prd.py
    Parsing settings.json
    Eta set automatically to: 0.94
    Clamp_max automatically set to 0.05
    clip_guidance_scale set automatically to: 50000
    Using device: cuda:0
    512 Model already downloaded, check check_model_SHA if the file is corrupt
    Secondary Model already downloaded, check check_model_SHA if the file is corrupt
    Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
    Loading model from: C:\Users\bruno\miniconda3\envs\progrockdiffusion\lib\site-packages\lpips\weights\v0.1\vgg.pth
    Will save every 19 steps
    Traceback (most recent call last):_
      **File ".\prd.py", line 2740, in <module>
        batchNum = max(filenums) + 1
    ValueError: max() arg is an empty sequence**

**Comment by hydropix** [comment]
I fixed it with
 if not filenums:
        batchNum = 0
    else:
        batchNum = max(filenums) + 1

**Comment by lowfuel** [comment]
Thanks, I fixed this yesterday, if you grab the latest version it should be good (essentially the same fix you made).
