### ISSUE TITLE
What does stop_early do?

### ISSUE THREAD

**Issue by ikarth** [lowfuel/progrockdiffusion#38]
The `stop_early` option is currently undocumented.

I see that it cuts off the loop when `cur_t` exceeds `stop_early`, but since it is undocumented I'm not clear on what it is doing. It looks like `cur_t` is just the remaining timesteps, so `stop_early` just stops at a fixed number of steps before the otherwise scheduled in? What's the reason for it?

**Comment by lowfuel** [comment]
Sometimes an image looks quite good when it's 90% done, but can go a bit overboard towards the end, so I suppose it could be useful in the scenario.

Also you may just be creating a compositional image to use as an init later, so there's no need to wait for the full render, especially if you're creating a lot of them to get one with a composition you like.
