### ISSUE TITLE
[Idea] GUI support?

### ISSUE THREAD

**Issue by lendrick** [lowfuel/progrockdiffusion#4]
A while back I was using a Colab notebook that let you pause image generation and either paint over things you don't like or set a mask for what would actually be affected.  It would be cool to have a pause button that would let you edit the image mid-generation (maybe by opening it in your favorite paint program and then detecting when it's been saved), or even alter some settings (like the prompt, etc).  Also, just being able to watch the image generation every frame would be really nice.

I can give this a shot if it sounds good.  Thoughts?

**Comment by lowfuel** [comment]
A basic GUI was added by Incognit0 a while back.
