### ISSUE TITLE
Some numerical settings are clamped arbitrarily?

### ISSUE THREAD

**Issue by Letiliel** [lowfuel/progrockdiffusion#41]
For example, clamp_max is clamped at 0.1 on Progrock while higher values are accepted by the "underlying code" and can give very interesting results.
This is some mandala thing with an init, [at 0.1](https://cdn.discordapp.com/attachments/843487975357808654/980498900312014888/Mandalas_32_0.png) as allowed by Progrock, and [at 0.3](https://cdn.discordapp.com/attachments/843487975357808654/980498901020839946/Mandalas_34_0.png)

I think clamping settings should only be done for values that would result in an error. Let the users explore the full range of possible values!

**Comment by lowfuel** [comment]
Thanks. I've increased clamp_max to .3. These were all set to Zippy's guide, which was since updated for clamp_max so it now matches again. You are of course welcome to change the values in your local copy! Or if you prefer I can add a command-line switch that prevents it from doing these checks.

**Comment by Letiliel** [comment]
Ah I see!
A CLI flag to turn off the clamping would be nice yes, as the ranges in Zippy's guide seem to be empirical. They also say for instance "as with most DD parameters, you can go below zero for eta", but the suggested range is 0 - 1.0

**Comment by lowfuel** [comment]
Ok, cool. I will add a flag to skip the clamping then. Should have it in later today.

**Comment by Letiliel** [comment]
Awesome, thank you!

**Comment by lowfuel** [comment]
Checked in with a --skip_checks cli flag. I only did cursory testing, so let me know if you run into any trouble.

**Comment by Letiliel** [comment]
Thanks! 
Is there a way I can support your work, Patreon or else?

**Comment by lowfuel** [comment]
Appreciate the offer! Not at the moment, though I've been considering that lately as this is taking up a lot more time than I'd anticipated. Keep an eye on the main page, I may add a patreon or similar soon.

**Comment by lowfuel** [comment]
Hey, I decided to try it out, so here's a link to my patreon: https://www.patreon.com/jasonmhough?fan_landing=true
Appreciate any support!
