### ISSUE TITLE
TypeError: ddim_sample_loop_progressive() got an unexpected keyword argument 'skip_timesteps'

### ISSUE THREAD

**Issue by Letiliel** [lowfuel/progrockdiffusion#43]
I'm getting that error after pulling the last commits:

Traceback (most recent call last):
  File "prd.py", line 3027, in <module>
    do_run()
  File "prd.py", line 1662, in do_run
    samples = do_sample_fn(init, steps - cur_t - 1)
  File "prd.py", line 1629, in do_sample_fn
    samples = sample_fn(
TypeError: ddim_sample_loop_progressive() got an unexpected keyword argument 'skip_timesteps'

**Comment by lowfuel** [comment]
Interesting. I'll have a look!

**Comment by lowfuel** [comment]
I just did a fresh git pull and it's running here. ddim_sample_loop_progressive is a function inside guided diffusion I believe, maybe try pulling that again? I wonder if it was updated and has broken something. I will check too.

**Comment by Letiliel** [comment]
Ah yes it works after reinstalling guided_diffusion, thank you :)
