### ISSUE TITLE
CLIP doesn't respect cuda device passed in via CLI args

### ISSUE THREAD

**Issue by kjhenner** [lowfuel/progrockdiffusion#49]
Running with the "--cuda 1" arg, I see the "Using device: cuda:1" printed, but still get a memory allocation error when cuda:0's memory usage is high. Adding debug break before `CLIP/clip/clip.py` I can see that it's just using the string 'cuda' as the device identifier without any index.

**Comment by kjhenner** [comment]
It looks like we're loading the model *without* specifying a device, then moving it to the specified device after:
https://github.com/lowfuel/progrockdiffusion/blob/main/prd.py#L2507
That load method takes a device param, so we should be able to put it in directly. I'll see if that fixes it, then make a PR.

**Comment by lowfuel** [comment]
Thanks! Let me know how it goes.

**Comment by kjhenner** [comment]
Made a PR--let me know if that looks good! Have validated that I can run on two devices at once and that CPU mode still works (though it's glacially slow, so I didn't let it finish a run)

**Comment by lowfuel** [comment]
I'll check it out right away. I'm hopeful this might also fix the random out of memory issues some people have reported.

**Comment by kjhenner** [comment]
Just noticed I left in a commented out line I was using to test. Just leaving a note here so I remember to go back and clean that up. I *think* the current uncommented line is as it should be... :)
