### ISSUE TITLE
How is this code base getting synced with the DD GtHub common project

### ISSUE THREAD

**Issue by ericsilvertx** [lowfuel/progrockdiffusion#52]
This looks like a fork but they now are at version 5.3.

I love the concept of batch mode

**Comment by bluejorts** [comment]
Any chance of doing vertical and horizontal symmetry in PRD?

**Comment by lowfuel** [comment]
Vertical is in there already (as of a few weeks ago, so you might need to grab the latest version). I can look at horizontal as well, I imagine it's fairly easy to add.

**Comment by lowfuel** [comment]
Horizontal symmetry is in now too.
