### ISSUE TITLE
Cannot import 'NoneType' from 'types'

### ISSUE THREAD

**Issue by kjhenner** [lowfuel/progrockdiffusion#56]
Looks like the recent change caused a problem. I'm using Python 3.7.13.
```
Traceback (most recent call last):
  File "prd.py", line 112, in <module>
    from types import NoneType, SimpleNamespace
ImportError: cannot import name 'NoneType' from 'types' (/home/kevin/anaconda3/envs/progrockdiffusion/lib/python3.7/types.py)
```
Is there a reason we need to check for for the type instead of just None?

**Comment by lowfuel** [comment]
I thought that's what I did, but after your comment I went and looked. It seems VS Code tried to do something smart? I did not add the import for NoneType, for example. Not really sure what happened there (I'm new to VS Code). Anyway, thanks for catching this and suggesting the fix.
