### ISSUE TITLE
FYI - my GPU is toast

### ISSUE THREAD

**Issue by lowfuel** [lowfuel/progrockdiffusion#58]
Might be slow to roll out stuff for a while as it will be cumbersome to rely on CPU mode.

**Comment by kjhenner** [comment]
That sucks man! Glad to help out where I can.

**Comment by lowfuel** [comment]
Limping along again after adjusting fan curve and limiting its power draw, but it's definitely unstable. 
I will probably have to bite the bullet and get a new card soon. Luckily they're in stock again and not egregiously marked up.
