### ISSUE TITLE
First run gives error.

### ISSUE THREAD

**Issue by KnoBuddy** [lowfuel/progrockdiffusion#70]
`Traceback (most recent call last):
   File "prd.py", line 3244, in <module>
      do_run()
   File "prd.py", line 1855, in do_run
      for j, sample in enumerate(samples):
   File "/home/kyle/progrockdiffusion/guided-diffusion/guided_diffusion.py", line 867, in ddim_sample_loop_progressive
      img = th.randn(*shape, device=device)
TypeError: randn(): argment 'size' must be tuple of ints, but found element of type float at pos 3`

I may just give up on this GCE linux install for favor of windows server 2022 or continue using DD. Idk centipede diffusion was looking nice too but I had errors when running it initially.

**Comment by lowfuel** [comment]
That's a new one to me. Is this a fresh install using the default settings? Any additional info you can provide would be great.

**Comment by KnoBuddy** [comment]
Fresh install on GCP. Followed instructions exactly. Compy and paste etc.

I'm pretty good with Linux and ran into other issues before the install but
once I finally got anaconda installed with which I am fairly well versed
and it went smoothly right up until I ran the first prompt.

I'll probably end up going the windows route as using Google RDP is
annoying vs actual display drivers.

**Comment by KnoBuddy** [comment]
Are you running windows or Linux?

**Comment by KnoBuddy** [comment]
Actually you know it did throw an error about numpy being the wrong version for pandas. It said the installed version was like 1.22 and the required version needed to be greater than 1.16, 1.17 was recommended. So I installed 1.17 and the error went away but then I got this.

Idk it was late last night and I'm finishing a windows install on my local machine right now. I have to head to work but my be able to RDP in and see if it runs.

**Comment by KnoBuddy** [comment]
So this just happened in my windows install same thing that happened in Linux before throwing the above error. 

`Traceback (most recent call last):                                                                                        File "prd.py", line 101, in <module>                                                                                      import pandas as pd                                                                                                   File "C:\Users\kyle\anaconda3\envs\progrock\lib\site-packages\pandas\__init__.py", line 22, in <module>                   from pandas.compat import (                                                                                           File "C:\Users\kyle\anaconda3\envs\progrock\lib\site-packages\pandas\compat\__init__.py", line 15, in <module>            from pandas.compat.numpy import (                                                                                     File "C:\Users\kyle\anaconda3\envs\progrock\lib\site-packages\pandas\compat\numpy\__init__.py", line 27, in <module>      f"this version of pandas is incompatible with numpy < {_min_numpy_ver}\n"                                           ImportError: this version of pandas is incompatible with numpy < 1.17.3                                                 your numpy version is 1.16.6.`

**Comment by KnoBuddy** [comment]
That fixed it. Thanks

**Comment by KnoBuddy** [comment]
It probably would have fixed the Linux version too. The readme should probably be amended to fix the install instructions so this doesn't happy.

**Comment by lowfuel** [comment]
Weirdly most of the time it doesn't happen, hence its not in the main instructions. But I'll take that into consideration!
