### ISSUE TITLE
weight in prompt throws an error

### ISSUE THREAD

**Issue by nikocraft** [lowfuel/progrockdiffusion#74]
Can't get weights in prompt working, always getting an error 

![image](https://user-images.githubusercontent.com/443080/175765775-8ae308f9-b1a2-4de7-a19f-357092f62b64.png)

**Comment by lowfuel** [comment]
Hi there! A prompt weight has to go at the end of a prompt, and they have to not add up to 0. Perhaps try something like this:

"Rain in a tropical jungle, matte painting by Esao Andrews, Trending on Artstation:2", "umbrella:-1"

**Comment by nikocraft** [comment]
Thank you will try that! :)

**Comment by lowfuel** [comment]
I might try to detect this and print out a more helpful error. :D

**Comment by nikocraft** [comment]
Thank you Jason, you just got a new supporter on Patreon! :)

**Comment by lowfuel** [comment]
Literally doubling my patreon count. :) Thank you!!

**Comment by nikocraft** [comment]
My pleasure! :)
