### ISSUE TITLE
Pixel art diffusion model doesn't work well

### ISSUE THREAD

**Issue by fanpeizhou** [lowfuel/progrockdiffusion#78]
When I changed the diffusion model to "pixel_art_diffusion_hard_256"(and soft),  the program errors occurred. Then I added "pixel_art_diffusion" items in "ram_helpers.py" file by imitating "512*512_difusion" items . It works, but the output is awful. I guess it is the parameters issue of "weight_and_grad_size", "init_px_coef" and "loss_px_coef". And I have no idea to set them.

**Comment by lowfuel** [comment]
I'll take a look, thanks for reporting it.

**Comment by kjhenner** [comment]
I've got a PR that addresses that error. @fanpeizhou those parameters you mention are just used to estimate model VRAM usage--they won't have an impact on the model results. I've only played with that pixel art model a little bit, but I found it pretty challenging to get good results from it.

**Comment by fanpeizhou** [comment]
> 

Thanks you very much for the quick reply!

**Comment by fanpeizhou** [comment]
> I've got a PR that addresses that error. @fanpeizhou those parameters you mention are just used to estimate model VRAM usage--they won't have an impact on the model results. I've only played with that pixel art model a little bit, but I found it pretty challenging to get good results from it.

Oh, thanks for the reminder. Yes, pretty hard to get good results. Now I'm perusing the SETTINGS.md :)

**Comment by fanpeizhou** [comment]
> I'll take a look, thanks for reporting it.

Thanks you very much for the quick reply!

**Comment by lowfuel** [comment]
Sure thing. The fix for unknown models is in now!
