### ISSUE TITLE
symmetry problems

### ISSUE THREAD

**Issue by merecesarchviz** [lowfuel/progrockdiffusion#81]
I´m been testing it as you recommend in the settings but the results are strange, and dont looks that have symmetry applied!

Here is the settings changed to do the symmetry:

    symmetry_loss_v: true,
    symmetry_loss_h: false,
    sloss_scale: 2400,
    symm_switch: 300,

I did a comparation adding the same prompt in colab disco diffusion with symmetry activated and in progrockdiffusion and as you can see in the image below the DD is doing the symmetry but the progrockdiffusion one is not doing it, we can´t see symmetry, any idea what is happening?

![descarregar](https://user-images.githubusercontent.com/79140456/175913510-b0c9ca3a-8574-454a-ab7d-b78d4ec39c49.png)

**Comment by lowfuel** [comment]
Not sure! Maybe something broke. I'll look into it today. Can you send me your output settings file that went with that image?

**Comment by lowfuel** [comment]
I think I found the issue. You can perhaps temporarily fix it on your end by:

- Making sure symm_switch is less than your total steps
- Crank up the symm_loss value to 100000 or so (play with this).

**Comment by lowfuel** [comment]
Okay, fix is in. Evidently when horizontal symmetry was added we accidentally picked up some extra code that was treating the symm_switch as a percentage rather than a step, so it was doing weird stuff when you had a high number, and not doing anything at all if it was more than the actual steps configured.

Give it a try and let me know if it's better. Also, you will need a new file with this update, diffusion_models.json, so make sure you grab that, too.

**Comment by merecesarchviz** [comment]
I try with the suggested settings:

Making sure symm_switch is less than your total steps
Crank up the symm_loss value to 100000 or so (play with this).

but still not get the symmetry! always one of the sides is very different from the other!

**Comment by lowfuel** [comment]
Did you grab the new code?

**Comment by merecesarchviz** [comment]
no, how i can update it?

**Comment by lowfuel** [comment]
I think you can just do "git pull" while in your progrockdiffusion directory, however if you've changed any files it might error out, so you'll want to move those to another directory first.

**Comment by lowfuel** [comment]
Excellent!
As for the sloss_scale value, I think basically the higher it is the more symmetrical the two sides will be. So play with it. You may want it lower so things aren't quite so perfect, but that's a stylistic choice. I'm getting good results at 20000 or so.
