### ISSUE TITLE
suggestion for handling metadata

### ISSUE THREAD

**Issue by nikocraft** [lowfuel/progrockdiffusion#84]
Hi Jason, could you expose handling meta data in settings.json so user can decide if he wants metadata or not.

Talking about this setting here. I have to flip it to false, but then I have to keep doing this everytime I pull the latest changes since I do not plan to commit this change.

![image](https://user-images.githubusercontent.com/443080/176482672-8e11ab60-dc28-4e06-b7a0-23f00b569817.png)

if you expose it in either settings.json OR some other settings file that is read by prd.py, and by default have it false, that would be nice :)

**Comment by lowfuel** [comment]
Yes, I could put that in the settings file. You can also add the command line switch --hidemetadata
Alternatively (or additionally), maybe an environment variable so you don't have to remember to change it between updates?

Personally I prefer it on by default, and will simply remove the metadata by hand if I have an image I want to share without my settings being revealed.

**Comment by nikocraft** [comment]
yes env variable will work for me, kept in an .env file. We can take that route if it works for you too :) you can keep it true by default, no problems:) thank you for all your effort to bring this tool to us :)

**Comment by lowfuel** [comment]
I don't know what an env file is. What operating system?
If Windows PowerShell you would type this at the command line:

$env:PRD_HIDE_METADATA = "TRUE"

**Comment by nikocraft** [comment]
I never worked with python extensivly, I assumed this was more or less done for every python project. See attached screenshot

![image](https://user-images.githubusercontent.com/443080/176751484-211cff9b-f91b-4c39-ac30-f013786073d3.png)

Since it was included in your gitignore, I assumed project already supported it
![image](https://user-images.githubusercontent.com/443080/176751603-45be0112-16fc-4e35-8bb7-235dda9a6da3.png)

**Comment by lowfuel** [comment]
Sorry, I'm not familiar with that feature. The gitignore is standard issue. I'll see about supporting that method when I return from my trip, in the meantime you can use a regular environment variable or the command line option.

**Comment by nikocraft** [comment]
I'll switch to command line option, seems cleaner then setting env in powershell directly.

**Comment by nikocraft** [comment]
Sure that can also work, since I'm only using conda for rock diffusion I do not mind having to set variables globaly like that, it will work. Also by now I'm used to also just run with --hidemetadata

**Comment by lowfuel** [comment]
Okay, great! Going to mark this as closed, then. We can revisit later if additional options or methods are preferred.
