### ISSUE TITLE
Feature suggestion: Terminate image cooking cetain steps before end

### ISSUE THREAD

**Issue by nikocraft** [lowfuel/progrockdiffusion#88]
Hi James

here is a feature that would be usefull, sometimes image look much better certain amount of steps before the end is reached. Image can look better at 95% then 100%.

Could you introduce a feature in settings.json where we can terminate diffusion process before image is "overcooked"?  For example allow us to control amount of steps before the end that the process will just stop.

I've currently had to use intermediate saves to extract the image but it's a hack to do it that way, if you generate 100's of images in a single batch, having to do this for all images is lots of work. 

This feature is also something someone else asked for in DD discord server, so I'm not the only one wishing for this to be a setting that one can easily flip on/off.

this is the end result, not looking bad, but it sometimes can feel like it would have looked better if cooking was terminated earlier.
![Ancient Cities_23_1](https://user-images.githubusercontent.com/443080/177333690-70e3e556-1da0-4001-bbb0-d0c09bbc3a89.png)

This is desired result, less "overcooked"
![Ancient Cities(23)_0001-88%](https://user-images.githubusercontent.com/443080/177334004-252a737b-2a35-4f0c-af24-6c7dfd60ee6b.png)

**Comment by nikocraft** [comment]
Amazing, looking foward to using it! :)

**Comment by lowfuel** [comment]
stop_early should be fine with the code you already have (though I must admit I haven't tried it in a while and a lot has changed, so let me know if it gives you any problems)

**Comment by nikocraft** [comment]
Btw Disney + VFX people, I've sent them here, I post regulary some of my work on  LinkedIn and one of them asked what program I was using locally to be able to create such a work. They may use rock diffusion in pre-production, who knows :) All kind of studios are now looking at ways to get in the game.

**Comment by hydropix** [comment]
I confirm for several months, the video game industry (myself) and cinema (some friends), already use it. On very big productions.

**Comment by lowfuel** [comment]
That's so cool to hear. And dang, I really need to stop fiddling with the code and start making some images... a job offer or two would be neat. :)
