### ISSUE TITLE
Simplify the installation process

### ISSUE THREAD

**Issue by roma-glushko** [lowfuel/progrockdiffusion#9]
Hey it's glad to see someone adapted the disco diffusion to a console use 👍 

Would you be interested in using requirements.txt and submodules in order to simplify installation process?

**Comment by lowfuel** [comment]
Appreciate the suggestion! I actually tried early on, but kept running into problems so I gave up. Disco seems to have a delicate install...

I wonder if a script might work better? 

Anyway, if someone wants to tackle this I'm all for it, but at the moment it's lower on my own priority list.

**Comment by roma-glushko** [comment]
@lowfuel Thank you for the response! I can try to contribute to that one if you find this useful

**Comment by lowfuel** [comment]
Sure, any help is appreciated! Forgive me, I'm actually fairly new to github (and python for that matter), do I need to make you a contributor to do that? I assume you'll just branch of main and make a pull request when you're ready with something?

**Comment by roma-glushko** [comment]
@lowfuel no problem at all! You could make me a contributor but I can also work without that by forking the repository and making some changes in my own copy of it. Then, I will be able to create a PR into the original repository. So no worries about that.

**Comment by lowfuel** [comment]
Okay. Whichever you prefer really, I have no preference. Just let me know!

**Comment by lowfuel** [comment]
@roma-glushko by the way what's the easiest way for me to try your setup changes? Is there a way I can clone this pull request? I've only ever cloned the base project or a branch.

**Comment by roma-glushko** [comment]
@lowfuel looks like you can clone my fork as a separate project and then configure a venv for it. After that, try to run `pip install` commands that I have added to readme.md file. The installation should go fine and then it should be possible to run `prd.py` without `lib/module not found` errors

**Comment by lowfuel** [comment]
I ran into two problems so far: 

1. Couldn't find resize_right (I don't see it in the requirements txt)
2. Couldn't find cv2, which might be because the "conda install opencv" command isn't in your readme? It went away after I ran it so I think it might still be necessary.

**Comment by lowfuel** [comment]
I think all the issues with this are resolved now. After a few more tests I will merge in from the simpleinstall branch.

**Comment by roma-glushko** [comment]
Awesome, it was great to help with this one 👍
