### ISSUE TITLE
Image prompts

### ISSUE THREAD

**Issue by iceandstorm** [lowfuel/progrockdiffusion#93]
Hi, I try to get image prompts to function, but I am at a total loss with the syntax to-do that… even frantic googling did not yield a lot of information… how do I set image prompts?

**Comment by lowfuel** [comment]
Okay, so it seems to be working for me. I do need to make some tweaks so it's easier to only have an image prompt (with no text prompt), but right now I think you might have to set both.

Anyway, here's an example of using an image prompt in a settings file:
```
    "image_prompts": {
        "0": [
            "init_images/flower.jpg"
        ],
    },
```
This would use "flower.jpg" from within the init_images folder, but you can of course specify whatever image or path you need. Also, I believe you can also supply a URL to an image, if that's easier.

Note: You may need to grab the latest version of prog rock in order for image prompts to work, as some fixes were recently made.

**Comment by lowfuel** [comment]
Definitely grab the latest version and let me know. Thanks!

**Comment by hydropix** [comment]
You have not created a conda environment for progrockdiffusion, or you have not activated it? Try to follow my tutorial here  https://youtu.be/pBS-FzOFbFU

**Comment by lowfuel** [comment]
It says:
```
(base) PS C:\Users\thoma\progrockdiffusion> python prd.py
```
The "base" part implies you haven't activated the conda environment you made during the install process. Let me know if that helps you solve it. If not, we can get on Zoom or something and you can share your screen with me. We'll figure it out!

**Comment by merecesarchviz** [comment]
Hi,

I also re install the new files but i can´t use the image prompts because give errors, any idea what is wrong!?

![image](https://user-images.githubusercontent.com/79140456/177873128-cd72e21e-60fe-4550-a56b-58cafb1ea794.png)

**Comment by lowfuel** [comment]
Can you post the settings you used for both text_prompts and image_prompts? Looks like you've got an _ character in your text_prompts which is causing it to try and use the randomizer feature.

**Comment by lowfuel** [comment]
So that's in the "text_prompts" section. You need to change it to "image_prompts".
But also, note that you may still need a text_prompts as I think right now it might not like having no text prompt.

You could do something like:
```
// It is recommended that you DO NOT edit this file. Instead, make a copy that contains the settings you wish to change, 
// then simply specify your copy on the command line:
// For example:
// python prd.py -s my_settings.json
{
    "batch_name": "Default",
    "text_prompts": {
        "0": [
            "Here is a text prompt that describes the image."
        ]
    },
    "image_prompts": {
        "0": [
            "init_images/1.jpg"
        ]
    },
(and then the rest of the settings)
```

**Comment by merecesarchviz** [comment]
Now working! thks
