### ISSUE TITLE
Feature Suggestion: Save Partials

### ISSUE THREAD

**Issue by LuisBurdallo** [lowfuel/progrockdiffusion#95]
Any chance we can have that? At least I haven't seen anything in the settings.

**Comment by lowfuel** [comment]
Hi Luis: I think what you need is already there: intermediate_saves

```"intermediate_saves": [.7, .8, .9]```

Would save an image at 70%, 80%, and 90% of steps.
If you want a specific step number instead of a percentage just use a whole number.

Let me know if that works for you!

**Comment by LuisBurdallo** [comment]
> Hi Luis: I think what you need is already there: intermediate_saves
> 
> `"intermediate_saves": [.7, .8, .9]`
> 
> Would save an image at 70%, 80%, and 90% of steps. If you want a specific step number instead of a percentage just use a whole number.
> 
> Let me know if that works for you!

Oh! you see I was looking for partials... Thanks a lot for that.
