### ISSUE TITLE
Sugg: save as jpg?

### ISSUE THREAD

**Issue by Letiliel** [lowfuel/progrockdiffusion#97]
Those uncompressed PNG files are heavy!

**Comment by lowfuel** [comment]
I think the output module supports jpg. Will try it!

**Comment by lowfuel** [comment]
Yeah it works fine. Checked it in.
In the settings file look for (or add to your own):
```
"use_jpg": false
```
And change it to true if you prefer to use jpeg.
Note: You will lose the storing of metadata in the image.

**Comment by Letiliel** [comment]
Ah thanks but it seems it's saving with 75 quality, which is a little to destructive IMO, are you able change that? I'd use 95 by default, it cuts the png size by about 3 and quality degradation is unnoticeable.

**Comment by lowfuel** [comment]
I'll check and see if there's a quality option. More soon...

**Comment by lowfuel** [comment]
Yep, all set. Jpg at 95 quality.

**Comment by Letiliel** [comment]
Perfecto, thank you :]
